      PROGRAM PSILIN_PARITY_DRIVER
      INCLUDE 'XFOIL.INC'
C
      INTEGER CASECOUNT, CASEINDEX, NODECOUNT, FIELDINDEX
      INTEGER INCLUDESOURCETERMSINT, SHARPTRAILINGEDGEINT
      INTEGER NODEINDEX, CURRENTCASE, I2, I3
      LOGICAL INCLUDESOURCETERMS, GEOMETRICSENSITIVITIES
      REAL FIELDX, FIELDY, FIELDNORMALX, FIELDNORMALY
      REAL FREESTREAMSPEED, ANGLEOFATTACK
      REAL PSI, PSINI
      COMMON /PSILIN_DRIVER_STATE/ CURRENTCASE
C
      GEOMETRICSENSITIVITIES = .FALSE.
C
      READ(*,*) CASECOUNT
      WRITE(*,'(I8)') CASECOUNT
C
      DO 100 CASEINDEX = 1, CASECOUNT
        CURRENTCASE = CASEINDEX
        READ(*,*) NODECOUNT, FIELDINDEX, INCLUDESOURCETERMSINT,
     &            SHARPTRAILINGEDGEINT
        READ(*,*) FIELDX, FIELDY, FIELDNORMALX, FIELDNORMALY
        READ(*,*) FREESTREAMSPEED, ANGLEOFATTACK
        READ(*,*) DSTE, ANTE, ASTE
C
        N = NODECOUNT
        SHARP = SHARPTRAILINGEDGEINT .NE. 0
        INCLUDESOURCETERMS = INCLUDESOURCETERMSINT .NE. 0
        ALFA = ANGLEOFATTACK
        QINF = FREESTREAMSPEED
        PI = ACOS(-1.0)
        HOPI = 0.5 / PI
        QOPI = 0.25 / PI
C
        DO 10 NODEINDEX = 1, NODECOUNT
          READ(*,*) X(NODEINDEX), Y(NODEINDEX), S(NODEINDEX),
     &              APANEL(NODEINDEX), GAM(NODEINDEX), SIG(NODEINDEX)
   10   CONTINUE
C
        CALL PSILIN(FIELDINDEX + 1, FIELDX, FIELDY,
     &              FIELDNORMALX, FIELDNORMALY,
     &              PSI, PSINI,
     &              GEOMETRICSENSITIVITIES, INCLUDESOURCETERMS)
C
        I2 = MIN0(2, NODECOUNT)
        I3 = MIN0(3, NODECOUNT)
        WRITE(*,1000) CURRENTCASE, FIELDINDEX + 1,
     &                TRANSFER(PSI, 0), TRANSFER(PSINI, 0),
     &                TRANSFER(DZDG(1), 0), TRANSFER(DZDG(I2), 0),
     &                TRANSFER(DZDG(I3), 0), TRANSFER(DZDG(NODECOUNT), 0),
     &                TRANSFER(DZDM(1), 0), TRANSFER(DZDM(I2), 0),
     &                TRANSFER(DZDM(I3), 0), TRANSFER(DZDM(NODECOUNT), 0),
     &                TRANSFER(DQDG(1), 0), TRANSFER(DQDG(I2), 0),
     &                TRANSFER(DQDG(I3), 0), TRANSFER(DQDG(NODECOUNT), 0),
     &                TRANSFER(DQDM(1), 0), TRANSFER(DQDM(I2), 0),
     &                TRANSFER(DQDM(I3), 0), TRANSFER(DQDM(NODECOUNT), 0)
 1000   FORMAT('FINAL',1X,I0,1X,I0,18(1X,Z8.8))
  100 CONTINUE
C
      END
