      INTEGER FUNCTION TRACE_LENTRIM(STR)
      CHARACTER*(*) STR
      INTEGER I
C
      TRACE_LENTRIM = LEN(STR)
      DO 10 I=LEN(STR),1,-1
        IF(STR(I:I).NE.' ') THEN
          TRACE_LENTRIM = I
          RETURN
        ENDIF
   10 CONTINUE
      TRACE_LENTRIM = 0
      RETURN
      END

      SUBROUTINE TRACE_ENSURE_OPEN(LOPEN)
      LOGICAL LOPEN
      INTEGER TRACE_LENTRIM, LPATH
      CHARACTER*1024 TRACEPATH
      LOGICAL ISOPEN
C
      TRACEPATH = ' '
      CALL GETENV('XFOIL_SPLINE_TRACE_PATH', TRACEPATH)
      LPATH = TRACE_LENTRIM(TRACEPATH)
      IF(LPATH.LE.0) THEN
        LOPEN = .FALSE.
        RETURN
      ENDIF
C
      INQUIRE(UNIT=71, OPENED=ISOPEN)
      IF(.NOT.ISOPEN) THEN
        OPEN(71, FILE=TRACEPATH(1:LPATH), STATUS='REPLACE')
      ENDIF
      LOPEN = .TRUE.
      RETURN
      END

      SUBROUTINE TRACE_OPEN(FILENAME)
      CHARACTER*(*) FILENAME
      LOGICAL LOPEN
C
      CALL TRACE_ENSURE_OPEN(LOPEN)
      RETURN
      END

      SUBROUTINE TRACE_CLOSE
      LOGICAL ISOPEN
C
      INQUIRE(UNIT=71, OPENED=ISOPEN)
      IF(ISOPEN) CLOSE(71)
      RETURN
      END

      SUBROUTINE TRACE_SPLINE_SYSTEM_ROW(SCOPE, ROUTINE, INDEX,
     & VALUE, PARAMETER, LOWER, DIAGONAL, UPPER, RHS,
     & STARTBOUNDARYCONDITION, ENDBOUNDARYCONDITION, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE
      CHARACTER*(*) STARTBOUNDARYCONDITION, ENDBOUNDARYCONDITION
      CHARACTER*(*) PRECISION
      INTEGER TRACE_LENTRIM, INDEX, LR
      REAL VALUE, PARAMETER, LOWER, DIAGONAL, UPPER, RHS
      LOGICAL LOPEN
C
      CALL TRACE_ENSURE_OPEN(LOPEN)
      IF(.NOT.LOPEN) RETURN
      LR = TRACE_LENTRIM(ROUTINE)
      IF(LR.LE.0) LR = 1
      WRITE(71,1000) ROUTINE(1:LR), INDEX, VALUE, PARAMETER,
     & LOWER, DIAGONAL, UPPER, RHS
 1000 FORMAT('spline_system_row,',A,',',I0,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16,',',
     & 1PE24.16,',',1PE24.16)
      RETURN
      END

      SUBROUTINE TRACE_SPLINE_SOLUTION_NODE(SCOPE, ROUTINE, INDEX,
     & VALUE, PARAMETER, DERIVATIVE,
     & STARTBOUNDARYCONDITION, ENDBOUNDARYCONDITION, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE
      CHARACTER*(*) STARTBOUNDARYCONDITION, ENDBOUNDARYCONDITION
      CHARACTER*(*) PRECISION
      INTEGER TRACE_LENTRIM, INDEX, LR
      REAL VALUE, PARAMETER, DERIVATIVE
      LOGICAL LOPEN
C
      CALL TRACE_ENSURE_OPEN(LOPEN)
      IF(.NOT.LOPEN) RETURN
      LR = TRACE_LENTRIM(ROUTINE)
      IF(LR.LE.0) LR = 1
      WRITE(71,1000) ROUTINE(1:LR), INDEX, VALUE, PARAMETER,
     & DERIVATIVE
 1000 FORMAT('spline_solution_node,',A,',',I0,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16)
      RETURN
      END

      SUBROUTINE TRACE_TRIDIAGONAL_FORWARD(SCOPE, ROUTINE, INDEX,
     & PIVOT, LOWER, UPPERBEFORE, RHSBEFOREPIVOT, UPPERAFTER,
     & RHSAFTERPIVOT, DIAGONALBEFORE, DIAGONALAFTER,
     & RHSBEFORE, RHSAFTER, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER TRACE_LENTRIM, INDEX, LR
      REAL PIVOT, LOWER, UPPERBEFORE, RHSBEFOREPIVOT, UPPERAFTER
      REAL RHSAFTERPIVOT, DIAGONALBEFORE, DIAGONALAFTER
      REAL RHSBEFORE, RHSAFTER
      LOGICAL LOPEN
C
      CALL TRACE_ENSURE_OPEN(LOPEN)
      IF(.NOT.LOPEN) RETURN
      LR = TRACE_LENTRIM(ROUTINE)
      IF(LR.LE.0) LR = 1
      WRITE(71,1000) ROUTINE(1:LR), INDEX, PIVOT, LOWER,
     & UPPERBEFORE, RHSBEFOREPIVOT, UPPERAFTER, RHSAFTERPIVOT,
     & DIAGONALBEFORE, DIAGONALAFTER, RHSBEFORE, RHSAFTER
 1000 FORMAT('tridiagonal_forward,',A,',',I0,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16,',',
     & 1PE24.16,',',1PE24.16)
      RETURN
      END

      SUBROUTINE TRACE_TRIDIAGONAL_LAST_PIVOT(SCOPE, ROUTINE, INDEX,
     & PIVOT, RHSBEFORE, RHSAFTER, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER TRACE_LENTRIM, INDEX, LR
      REAL PIVOT, RHSBEFORE, RHSAFTER
      LOGICAL LOPEN
C
      CALL TRACE_ENSURE_OPEN(LOPEN)
      IF(.NOT.LOPEN) RETURN
      LR = TRACE_LENTRIM(ROUTINE)
      IF(LR.LE.0) LR = 1
      WRITE(71,1000) ROUTINE(1:LR), INDEX, PIVOT, RHSBEFORE,
     & RHSAFTER
 1000 FORMAT('tridiagonal_last_pivot,',A,',',I0,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16)
      RETURN
      END

      SUBROUTINE TRACE_TRIDIAGONAL_BACK(SCOPE, ROUTINE, INDEX,
     & UPPER, NEXTVALUE, RHSBEFORE, RHSAFTER, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER TRACE_LENTRIM, INDEX, LR
      REAL UPPER, NEXTVALUE, RHSBEFORE, RHSAFTER
      LOGICAL LOPEN
C
      CALL TRACE_ENSURE_OPEN(LOPEN)
      IF(.NOT.LOPEN) RETURN
      LR = TRACE_LENTRIM(ROUTINE)
      IF(LR.LE.0) LR = 1
      WRITE(71,1000) ROUTINE(1:LR), INDEX, UPPER, NEXTVALUE,
     & RHSBEFORE, RHSAFTER
 1000 FORMAT('tridiagonal_back,',A,',',I0,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16)
      RETURN
      END

      SUBROUTINE TRACE_SPLINE_EVAL(SCOPE, ROUTINE, LOWERINDEX,
     & UPPERINDEX, PARAMETER, DSVAL, TVAL, VALUELOW, VALUEHIGH,
     & DERIVATIVELOW, DERIVATIVEHIGH, CX1, CX2, DELTA, FACTOR1,
     & FACTOR2, PRODUCT1, PRODUCT2, OPERAND1, OPERAND2,
     & OPERANDCOMBINED, ACCUMULATOR, VALUE, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER TRACE_LENTRIM, LOWERINDEX, UPPERINDEX, LR
      REAL PARAMETER, DSVAL, TVAL, VALUELOW, VALUEHIGH
      REAL DERIVATIVELOW, DERIVATIVEHIGH, CX1, CX2, DELTA
      REAL FACTOR1, FACTOR2, PRODUCT1, PRODUCT2, OPERAND1
      REAL OPERAND2, OPERANDCOMBINED, ACCUMULATOR, VALUE
      LOGICAL LOPEN
C
      CALL TRACE_ENSURE_OPEN(LOPEN)
      IF(.NOT.LOPEN) RETURN
      LR = TRACE_LENTRIM(ROUTINE)
      IF(LR.LE.0) LR = 1
      WRITE(71,1000) ROUTINE(1:LR), LOWERINDEX, UPPERINDEX,
     & PARAMETER, DSVAL, TVAL, VALUELOW, VALUEHIGH,
     & DERIVATIVELOW, DERIVATIVEHIGH, CX1, CX2, DELTA,
     & FACTOR1, FACTOR2, PRODUCT1, PRODUCT2, OPERAND1, OPERAND2,
     & OPERANDCOMBINED, ACCUMULATOR, VALUE
 1000 FORMAT('spline_eval,',A,',',I0,',',I0,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16,',',1PE24.16,',',
     & 1PE24.16,',',1PE24.16,',',1PE24.16)
      RETURN
      END

      SUBROUTINE TRACE_CURVATURE_EVAL(SCOPE, ROUTINE, LOWERINDEX,
     & UPPERINDEX, PARAMETER, DSVAL, T, XLOW, XHIGH, XSLOW,
     & XSHIGH, YLOW, YHIGH, YSLOW, YSHIGH, XFACTOR1, XFACTOR2,
     & YFACTOR1, YFACTOR2, XTERM1, XTERM2, YTERM1, YTERM2,
     & XD, XDD, YD, YDD, SD, CURVATURE, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER LOWERINDEX, UPPERINDEX
      REAL PARAMETER, DSVAL, T, XLOW, XHIGH, XSLOW, XSHIGH
      REAL YLOW, YHIGH, YSLOW, YSHIGH, XFACTOR1, XFACTOR2
      REAL YFACTOR1, YFACTOR2, XTERM1, XTERM2, YTERM1, YTERM2
      REAL XD, XDD, YD, YDD, SD, CURVATURE
      RETURN
      END

      SUBROUTINE TRACE_ARC_LENGTH_STEP(SCOPE, ROUTINE, INDEX,
     & DX, DY, SEGMENTLENGTH, CUMULATIVE, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER INDEX
      REAL DX, DY, SEGMENTLENGTH, CUMULATIVE
      RETURN
      END

      SUBROUTINE TRACE_SPLINE_SEGMENT(SCOPE, ROUTINE, SEGMENTSTART,
     & SEGMENTCOUNT, STARTBOUNDARYCONDITION,
     & ENDBOUNDARYCONDITION, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, STARTBOUNDARYCONDITION
      CHARACTER*(*) ENDBOUNDARYCONDITION, PRECISION
      INTEGER SEGMENTSTART, SEGMENTCOUNT
      RETURN
      END
