      PROGRAM SPLINE_PARITY_DRIVER
      IMPLICIT NONE
      INTEGER MAXN, MAXM
      PARAMETER (MAXN=64, MAXM=64)
      INTEGER TRACE_LENTRIM, TRACEPATHLEN
      INTEGER CASECOUNT, CASEINDEX, N, M, I
      REAL X(MAXN), XS(MAXN), S(MAXN), Q(MAXM)
      REAL XS1, XS2
      REAL SEVAL, DEVAL
      REAL VALUE, DERIV
      REAL XSBITVALUE, VALUEBITVALUE, DERIVBITVALUE
      INTEGER XSBITS, VALUEBITS, DERIVBITS
      CHARACTER*1024 TRACEPATH
      EQUIVALENCE (XSBITVALUE, XSBITS)
      EQUIVALENCE (VALUEBITVALUE, VALUEBITS)
      EQUIVALENCE (DERIVBITVALUE, DERIVBITS)
C
      TRACEPATH = ' '
      CALL GETENV('XFOIL_SPLINE_TRACE_PATH', TRACEPATH)
      TRACEPATHLEN = TRACE_LENTRIM(TRACEPATH)
      IF (TRACEPATHLEN.GT.0) THEN
        CALL TRACE_OPEN(TRACEPATH(1:TRACEPATHLEN))
      ENDIF
C
      READ(*,*) CASECOUNT
      WRITE(*,'(I8)') CASECOUNT
C
      DO 100 CASEINDEX = 1, CASECOUNT
        READ(*,*) N, M, XS1, XS2
        IF (N.GT.MAXN) STOP 'SPLINE_PARITY_DRIVER: MAXN exceeded'
        IF (M.GT.MAXM) STOP 'SPLINE_PARITY_DRIVER: MAXM exceeded'
C
        DO 10 I = 1, N
          READ(*,*) S(I), X(I)
   10   CONTINUE
C
        DO 20 I = 1, M
          READ(*,*) Q(I)
   20   CONTINUE
C
        CALL SPLIND(X, XS, S, N, XS1, XS2)
C
        WRITE(*,'(I8,1X,I8)') N, M
        DO 30 I = 1, N
          XSBITVALUE = XS(I)
          WRITE(*,'(Z8.8,1X,1PE24.16)') XSBITS, XS(I)
   30   CONTINUE
C
        DO 40 I = 1, M
          VALUE = SEVAL(Q(I), X, XS, S, N)
          DERIV = DEVAL(Q(I), X, XS, S, N)
          VALUEBITVALUE = VALUE
          DERIVBITVALUE = DERIV
          WRITE(*,'(Z8.8,1X,1PE24.16,1X,Z8.8,1X,1PE24.16)')
     &     VALUEBITS, VALUE, DERIVBITS, DERIV
   40   CONTINUE
  100 CONTINUE
C
      IF (TRACEPATHLEN.GT.0) THEN
        CALL TRACE_CLOSE
      ENDIF
C
      END
