      SUBROUTINE TRACE_SPLINE_SYSTEM_ROW(SCOPE, ROUTINE, INDEX,
     & VALUE, PARAMETER, LOWER, DIAGONAL, UPPER, RHS,
     & STARTBC, ENDBC, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, STARTBC, ENDBC, PRECISION
      INTEGER INDEX
      REAL VALUE, PARAMETER, LOWER, DIAGONAL, UPPER, RHS
      RETURN
      END


      SUBROUTINE TRACE_SPLINE_SOLUTION_NODE(SCOPE, ROUTINE, INDEX,
     & VALUE, PARAMETER, DERIVATIVE, STARTBC, ENDBC, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, STARTBC, ENDBC, PRECISION
      INTEGER INDEX
      REAL VALUE, PARAMETER, DERIVATIVE
      RETURN
      END


      SUBROUTINE TRACE_TRIDIAGONAL_FORWARD(SCOPE, ROUTINE, INDEX,
     & PIVOT, LOWER, UPPERBEFORE, RHSBEFOREPIVOT, UPPERAFTER,
     & RHSAFTERPIVOT, DIAGONALBEFORE, DIAGONALAFTER,
     & RHSBEFORE, RHSAFTER, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER INDEX
      REAL PIVOT, LOWER, UPPERBEFORE, RHSBEFOREPIVOT, UPPERAFTER
      REAL RHSAFTERPIVOT, DIAGONALBEFORE, DIAGONALAFTER
      REAL RHSBEFORE, RHSAFTER
      RETURN
      END


      SUBROUTINE TRACE_TRIDIAGONAL_LAST_PIVOT(SCOPE, ROUTINE, INDEX,
     & PIVOT, RHSBEFORE, RHSAFTER, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER INDEX
      REAL PIVOT, RHSBEFORE, RHSAFTER
      RETURN
      END


      SUBROUTINE TRACE_TRIDIAGONAL_BACK(SCOPE, ROUTINE, INDEX,
     & UPPER, NEXTVALUE, RHSBEFORE, RHSAFTER, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER INDEX
      REAL UPPER, NEXTVALUE, RHSBEFORE, RHSAFTER
      RETURN
      END


      SUBROUTINE TRACE_SPLINE_EVAL(SCOPE, ROUTINE, LOWERINDEX,
     & UPPERINDEX, PARAMETER, DSVAL, TVAL, VALUELOW, VALUEHIGH,
     & DERIVATIVELOW, DERIVATIVEHIGH, CX1, CX2, DELTA, FACTOR1,
     & FACTOR2, PRODUCT1, PRODUCT2, OPERAND1, OPERAND2,
     & OPERANDCOMBINED, ACCUMULATOR, VALUE, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER TRACE_LENTRIM, LSCOPE, LROUTINE, LPRECISION, LVERBOSE
      CHARACTER*32 VERBOSE
      INTEGER LOWERINDEX, UPPERINDEX
      REAL PARAMETER, DSVAL, TVAL, VALUELOW, VALUEHIGH
      REAL DERIVATIVELOW, DERIVATIVEHIGH, CX1, CX2, DELTA
      REAL FACTOR1, FACTOR2, PRODUCT1, PRODUCT2, OPERAND1
      REAL OPERAND2, OPERANDCOMBINED, ACCUMULATOR, VALUE
      VERBOSE = ' '
      CALL GETENV('XFOIL_SPLINE_STUB_VERBOSE', VERBOSE)
      LVERBOSE = TRACE_LENTRIM(VERBOSE)
      IF (LVERBOSE.GT.0) THEN
        LSCOPE = TRACE_LENTRIM(SCOPE)
        LROUTINE = TRACE_LENTRIM(ROUTINE)
        LPRECISION = TRACE_LENTRIM(PRECISION)
        IF (LSCOPE.LE.0) LSCOPE = 1
        IF (LROUTINE.LE.0) LROUTINE = 1
        IF (LPRECISION.LE.0) LPRECISION = 1
        WRITE(0,*) 'TRACE_SPLINE_EVAL',
     &   SCOPE(1:LSCOPE), ROUTINE(1:LROUTINE),
     &   LOWERINDEX, UPPERINDEX, PARAMETER, DSVAL, TVAL,
     &   VALUELOW, VALUEHIGH, DERIVATIVELOW, DERIVATIVEHIGH,
     &   CX1, CX2, DELTA, FACTOR1, FACTOR2, PRODUCT1, PRODUCT2,
     &   OPERAND1, OPERAND2, OPERANDCOMBINED, ACCUMULATOR,
     &   VALUE, PRECISION(1:LPRECISION)
      ENDIF
      RETURN
      END


      INTEGER FUNCTION TRACE_LENTRIM(STR)
      CHARACTER*(*) STR
      INTEGER I
      TRACE_LENTRIM = LEN(STR)
      DO 10 I = LEN(STR), 1, -1
        IF (STR(I:I).NE.' ') THEN
          TRACE_LENTRIM = I
          RETURN
        ENDIF
   10 CONTINUE
      TRACE_LENTRIM = 0
      RETURN
      END


      SUBROUTINE TRACE_CURVATURE_EVAL(SCOPE, ROUTINE, LOWERINDEX,
     & UPPERINDEX, PARAMETER, DSVAL, TVAL, XDEL, YDEL,
     & CX1, CX2, CY1, CY2,
     & XFAC1, XFAC2, YFAC1, YFAC2,
     & XTERM1, XTERM2, YTERM1, YTERM2,
     & XD, XDD, YD, YDD, SD, CURVATURE, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER LOWERINDEX, UPPERINDEX
      REAL PARAMETER, DSVAL, TVAL, XDEL, YDEL
      REAL CX1, CX2, CY1, CY2
      REAL XFAC1, XFAC2, YFAC1, YFAC2
      REAL XTERM1, XTERM2, YTERM1, YTERM2
      REAL XD, XDD, YD, YDD, SD, CURVATURE
      RETURN
      END


      SUBROUTINE TRACE_ARC_LENGTH_STEP(SCOPE, ROUTINE, INDEX,
     & DX, DY, SEGMENTLENGTH, CUMULATIVE, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, PRECISION
      INTEGER INDEX
      REAL DX, DY, SEGMENTLENGTH, CUMULATIVE
      RETURN
      END


      SUBROUTINE TRACE_SPLINE_SEGMENT(SCOPE, ROUTINE, SEGMENTSTART,
     & SEGMENTCOUNT, STARTBC, ENDBC, PRECISION)
      CHARACTER*(*) SCOPE, ROUTINE, STARTBC, ENDBC, PRECISION
      INTEGER SEGMENTSTART, SEGMENTCOUNT
      RETURN
      END
