using System;
using System.Collections.Generic;
using Xunit;
using XFoil.Solver.Models;
using XFoil.Solver.Services;

namespace XFoil.Core.Tests;

/// <summary>
/// Single-point viscous parity tests validating that the ported solver matches
/// Fortran XFoil 6.97 reference output within 0.001% for CL, CD, CM.
///
/// All reference values generated by running the Fortran XFoil 6.97 binary
/// from f_xfoil/ built via cmake/make on the same machine. Settings:
/// 160 panels, NCrit=9.0, Mach=0, free transition, no extended wake mods.
///
/// The tolerance is relative: |result - reference| / |reference| < 1e-5 (0.001%)
/// except for values near zero where absolute tolerance |result - reference| < 1e-7 is used.
/// Transition location tolerance: 1% x/c (absolute).
/// </summary>
public class ViscousParityTests
{
    // ================================================================
    // XFoil 6.97 Reference Values (from Fortran binary)
    // ================================================================

    // NACA 0012, Re=1e6, M=0, alpha=0, NCrit=9, 160 panels
    private const double Ref_0012_A0_CL = -0.0000;    // Near-zero for symmetric airfoil
    private const double Ref_0012_A0_CD = 0.00540;
    private const double Ref_0012_A0_CDf = 0.00427;
    private const double Ref_0012_A0_CDp = 0.00114;
    private const double Ref_0012_A0_CM = 0.0000;
    private const double Ref_0012_A0_Xtr_Top = 0.6871;
    private const double Ref_0012_A0_Xtr_Bot = 0.6872;

    // NACA 0012, Re=1e6, M=0, alpha=5, NCrit=9, 160 panels
    private const double Ref_0012_A5_CL = 0.5580;
    private const double Ref_0012_A5_CD = 0.00848;
    private const double Ref_0012_A5_CDf = 0.00543;
    private const double Ref_0012_A5_CDp = 0.00304;
    private const double Ref_0012_A5_CM = 0.0017;
    private const double Ref_0012_A5_Xtr_Top = 0.1486;
    private const double Ref_0012_A5_Xtr_Bot = 0.9849;

    // NACA 2412, Re=3e6, M=0, alpha=3, NCrit=9, 160 panels
    private const double Ref_2412_A3_CL = 0.5729;
    private const double Ref_2412_A3_CD = 0.00515;
    private const double Ref_2412_A3_CDf = 0.00384;
    private const double Ref_2412_A3_CDp = 0.00131;
    private const double Ref_2412_A3_CM = -0.0515;
    private const double Ref_2412_A3_Xtr_Top = 0.3652;
    private const double Ref_2412_A3_Xtr_Bot = 0.8944;

    // NACA 4415, Re=6e6, M=0, alpha=2, NCrit=9, 160 panels
    private const double Ref_4415_A2_CL = 0.7159;
    private const double Ref_4415_A2_CD = 0.00589;
    private const double Ref_4415_A2_CDf = 0.00463;
    private const double Ref_4415_A2_CDp = 0.00127;
    private const double Ref_4415_A2_CM = -0.1055;
    private const double Ref_4415_A2_Xtr_Top = 0.4081;
    private const double Ref_4415_A2_Xtr_Bot = 0.3532;

    // Tolerances
    private const double RelativeTolerance = 1e-5;        // 0.001% relative
    private const double AbsoluteZeroTolerance = 1e-7;    // For near-zero values
    private const double TransitionTolerance = 0.01;       // 1% x/c absolute

    // ================================================================
    // Test 1: NACA 0012, Re=1e6, alpha=0 (symmetric baseline)
    // ================================================================

    [Fact]
    public void Naca0012_Re1e6_Alpha0_CL_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 0.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=0 should converge");
        AssertNearZero(result.LiftCoefficient, Ref_0012_A0_CL,
            "CL for symmetric airfoil at alpha=0");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha0_CD_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 0.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=0 should converge");
        AssertRelativeMatch(result.DragDecomposition.CD, Ref_0012_A0_CD, "CD");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha0_CM_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 0.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=0 should converge");
        AssertNearZero(result.MomentCoefficient, Ref_0012_A0_CM,
            "CM for symmetric airfoil at alpha=0");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha0_DragDecomposition_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 0.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=0 should converge");
        AssertRelativeMatch(result.DragDecomposition.CDF, Ref_0012_A0_CDf, "CDF");
        AssertRelativeMatch(result.DragDecomposition.CDP, Ref_0012_A0_CDp, "CDP");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha0_Transition_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 0.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=0 should converge");
        AssertTransitionMatch(result.UpperTransition.XTransition, Ref_0012_A0_Xtr_Top, "upper");
        AssertTransitionMatch(result.LowerTransition.XTransition, Ref_0012_A0_Xtr_Bot, "lower");
    }

    // ================================================================
    // Test 2: NACA 0012, Re=1e6, alpha=5 (moderate lift)
    // ================================================================

    [Fact]
    public void Naca0012_Re1e6_Alpha5_CL_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 5.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=5 should converge");
        AssertRelativeMatch(result.LiftCoefficient, Ref_0012_A5_CL, "CL");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha5_CD_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 5.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=5 should converge");
        AssertRelativeMatch(result.DragDecomposition.CD, Ref_0012_A5_CD, "CD");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha5_CM_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 5.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=5 should converge");
        AssertRelativeMatch(result.MomentCoefficient, Ref_0012_A5_CM, "CM");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha5_DragDecomposition_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 5.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=5 should converge");
        AssertRelativeMatch(result.DragDecomposition.CDF, Ref_0012_A5_CDf, "CDF");
        AssertRelativeMatch(result.DragDecomposition.CDP, Ref_0012_A5_CDp, "CDP");
    }

    [Fact]
    public void Naca0012_Re1e6_Alpha5_Transition_MatchesXFoil()
    {
        var result = RunNaca0012(alpha: 5.0, re: 1_000_000);

        Assert.True(result.Converged, "NACA 0012 alpha=5 should converge");
        AssertTransitionMatch(result.UpperTransition.XTransition, Ref_0012_A5_Xtr_Top, "upper");
        AssertTransitionMatch(result.LowerTransition.XTransition, Ref_0012_A5_Xtr_Bot, "lower");
    }

    // ================================================================
    // Test 3: NACA 2412, Re=3e6, alpha=3 (cambered airfoil)
    // ================================================================

    [Fact]
    public void Naca2412_Re3e6_Alpha3_CL_MatchesXFoil()
    {
        var result = RunNaca2412(alpha: 3.0, re: 3_000_000);

        Assert.True(result.Converged, "NACA 2412 alpha=3 should converge");
        AssertRelativeMatch(result.LiftCoefficient, Ref_2412_A3_CL, "CL");
    }

    [Fact]
    public void Naca2412_Re3e6_Alpha3_CD_MatchesXFoil()
    {
        var result = RunNaca2412(alpha: 3.0, re: 3_000_000);

        Assert.True(result.Converged, "NACA 2412 alpha=3 should converge");
        AssertRelativeMatch(result.DragDecomposition.CD, Ref_2412_A3_CD, "CD");
    }

    [Fact]
    public void Naca2412_Re3e6_Alpha3_CM_MatchesXFoil()
    {
        var result = RunNaca2412(alpha: 3.0, re: 3_000_000);

        Assert.True(result.Converged, "NACA 2412 alpha=3 should converge");
        AssertRelativeMatch(result.MomentCoefficient, Ref_2412_A3_CM, "CM");
    }

    [Fact]
    public void Naca2412_Re3e6_Alpha3_DragDecomposition_MatchesXFoil()
    {
        var result = RunNaca2412(alpha: 3.0, re: 3_000_000);

        Assert.True(result.Converged, "NACA 2412 alpha=3 should converge");
        AssertRelativeMatch(result.DragDecomposition.CDF, Ref_2412_A3_CDf, "CDF");
        AssertRelativeMatch(result.DragDecomposition.CDP, Ref_2412_A3_CDp, "CDP");
    }

    [Fact]
    public void Naca2412_Re3e6_Alpha3_Transition_MatchesXFoil()
    {
        var result = RunNaca2412(alpha: 3.0, re: 3_000_000);

        Assert.True(result.Converged, "NACA 2412 alpha=3 should converge");
        AssertTransitionMatch(result.UpperTransition.XTransition, Ref_2412_A3_Xtr_Top, "upper");
        AssertTransitionMatch(result.LowerTransition.XTransition, Ref_2412_A3_Xtr_Bot, "lower");
    }

    // ================================================================
    // Test 4: NACA 4415, Re=6e6, alpha=2 (thick cambered airfoil)
    // ================================================================

    [Fact]
    public void Naca4415_Re6e6_Alpha2_CL_MatchesXFoil()
    {
        var result = RunNaca4415(alpha: 2.0, re: 6_000_000);

        Assert.True(result.Converged, "NACA 4415 alpha=2 should converge");
        AssertRelativeMatch(result.LiftCoefficient, Ref_4415_A2_CL, "CL");
    }

    [Fact]
    public void Naca4415_Re6e6_Alpha2_CD_MatchesXFoil()
    {
        var result = RunNaca4415(alpha: 2.0, re: 6_000_000);

        Assert.True(result.Converged, "NACA 4415 alpha=2 should converge");
        AssertRelativeMatch(result.DragDecomposition.CD, Ref_4415_A2_CD, "CD");
    }

    [Fact]
    public void Naca4415_Re6e6_Alpha2_CM_MatchesXFoil()
    {
        var result = RunNaca4415(alpha: 2.0, re: 6_000_000);

        Assert.True(result.Converged, "NACA 4415 alpha=2 should converge");
        AssertRelativeMatch(result.MomentCoefficient, Ref_4415_A2_CM, "CM");
    }

    [Fact]
    public void Naca4415_Re6e6_Alpha2_DragDecomposition_MatchesXFoil()
    {
        var result = RunNaca4415(alpha: 2.0, re: 6_000_000);

        Assert.True(result.Converged, "NACA 4415 alpha=2 should converge");
        AssertRelativeMatch(result.DragDecomposition.CDF, Ref_4415_A2_CDf, "CDF");
        AssertRelativeMatch(result.DragDecomposition.CDP, Ref_4415_A2_CDp, "CDP");
    }

    [Fact]
    public void Naca4415_Re6e6_Alpha2_Transition_MatchesXFoil()
    {
        var result = RunNaca4415(alpha: 2.0, re: 6_000_000);

        Assert.True(result.Converged, "NACA 4415 alpha=2 should converge");
        AssertTransitionMatch(result.UpperTransition.XTransition, Ref_4415_A2_Xtr_Top, "upper");
        AssertTransitionMatch(result.LowerTransition.XTransition, Ref_4415_A2_Xtr_Bot, "lower");
    }

    // ================================================================
    // Cross-validation: all test cases converge with XFoil-compatible settings
    // ================================================================

    [Fact]
    public void AllTestCases_Converge_WithXFoilCompatibleSettings()
    {
        var r1 = RunNaca0012(alpha: 0.0, re: 1_000_000);
        var r2 = RunNaca0012(alpha: 5.0, re: 1_000_000);
        var r3 = RunNaca2412(alpha: 3.0, re: 3_000_000);
        var r4 = RunNaca4415(alpha: 2.0, re: 6_000_000);

        Assert.True(r1.Converged, "NACA 0012 Re=1e6 alpha=0 should converge");
        Assert.True(r2.Converged, "NACA 0012 Re=1e6 alpha=5 should converge");
        Assert.True(r3.Converged, "NACA 2412 Re=3e6 alpha=3 should converge");
        Assert.True(r4.Converged, "NACA 4415 Re=6e6 alpha=2 should converge");
    }

    // ================================================================
    // Helper methods
    // ================================================================

    private static ViscousAnalysisResult RunNaca0012(double alpha, double re)
    {
        var settings = CreateXFoilParitySettings(re);
        var geometry = BuildNacaSymmetric0012(settings.PanelCount);
        return ViscousSolverEngine.SolveViscous(geometry, settings, alpha * Math.PI / 180.0);
    }

    private static ViscousAnalysisResult RunNaca2412(double alpha, double re)
    {
        var settings = CreateXFoilParitySettings(re);
        var geometry = BuildNacaCambered(0.02, 0.4, 0.12, settings.PanelCount);
        return ViscousSolverEngine.SolveViscous(geometry, settings, alpha * Math.PI / 180.0);
    }

    private static ViscousAnalysisResult RunNaca4415(double alpha, double re)
    {
        var settings = CreateXFoilParitySettings(re);
        var geometry = BuildNacaCambered(0.04, 0.4, 0.15, settings.PanelCount);
        return ViscousSolverEngine.SolveViscous(geometry, settings, alpha * Math.PI / 180.0);
    }

    /// <summary>
    /// Creates AnalysisSettings configured for XFoil parity testing:
    /// - ViscousSolverMode.XFoilRelaxation
    /// - UseModernTransitionCorrections = false
    /// - UseExtendedWake = false
    /// - InviscidSolverType = LinearVortex
    /// - PanelCount = 160 (matching XFoil default)
    /// - NCrit = 9.0
    /// </summary>
    private static AnalysisSettings CreateXFoilParitySettings(double reynoldsNumber)
    {
        return new AnalysisSettings(
            panelCount: 160,
            reynoldsNumber: reynoldsNumber,
            machNumber: 0.0,
            inviscidSolverType: InviscidSolverType.LinearVortex,
            viscousSolverMode: ViscousSolverMode.XFoilRelaxation,
            useModernTransitionCorrections: false,
            useExtendedWake: false,
            maxViscousIterations: 200,
            viscousConvergenceTolerance: 1e-4,
            criticalAmplificationFactor: 9.0);
    }

    /// <summary>
    /// Build NACA 0012 symmetric airfoil with cosine-spaced points (TE->LE upper, LE->TE lower).
    /// Matches XFoil's NACA generation: 4-digit, 0012, with the same thickness formula.
    /// </summary>
    private static (double[] x, double[] y) BuildNacaSymmetric0012(int n)
    {
        // Build as NACA XXYZ format: m=0, p=0, t=0.12
        return BuildNacaCambered(0.0, 0.0, 0.12, n);
    }

    /// <summary>
    /// Build a general NACA 4-digit airfoil with parameters (m, p, t).
    /// Generates (n+1) points: upper surface TE->LE then lower surface LE->TE.
    /// Uses cosine spacing matching XFoil's NACA paneling.
    /// </summary>
    private static (double[] x, double[] y) BuildNacaCambered(
        double m, double p, double t, int n)
    {
        int half = n / 2;
        double[] xCoords = new double[n + 1];
        double[] yCoords = new double[n + 1];

        for (int i = 0; i <= half; i++)
        {
            double theta = Math.PI * i / half;
            double xc = 0.5 * (1.0 + Math.Cos(theta)); // TE -> LE (1 -> 0)
            double yt = 5.0 * t * (0.2969 * Math.Sqrt(xc) - 0.1260 * xc
                - 0.3516 * xc * xc + 0.2843 * xc * xc * xc - 0.1036 * xc * xc * xc * xc);

            double yc = 0.0, dyc = 0.0;
            if (m > 0 && p > 0)
            {
                if (xc < p)
                {
                    yc = m / (p * p) * (2.0 * p * xc - xc * xc);
                    dyc = 2.0 * m / (p * p) * (p - xc);
                }
                else
                {
                    yc = m / ((1.0 - p) * (1.0 - p)) * (1.0 - 2.0 * p + 2.0 * p * xc - xc * xc);
                    dyc = 2.0 * m / ((1.0 - p) * (1.0 - p)) * (p - xc);
                }
            }

            double theta2 = Math.Atan(dyc);
            xCoords[i] = xc - yt * Math.Sin(theta2);
            yCoords[i] = yc + yt * Math.Cos(theta2);
        }

        for (int i = 1; i <= half; i++)
        {
            double theta = Math.PI * i / half;
            double xc = 0.5 * (1.0 - Math.Cos(theta)); // LE -> TE (0 -> 1)
            double yt = 5.0 * t * (0.2969 * Math.Sqrt(xc) - 0.1260 * xc
                - 0.3516 * xc * xc + 0.2843 * xc * xc * xc - 0.1036 * xc * xc * xc * xc);

            double yc = 0.0, dyc = 0.0;
            if (m > 0 && p > 0)
            {
                if (xc < p)
                {
                    yc = m / (p * p) * (2.0 * p * xc - xc * xc);
                    dyc = 2.0 * m / (p * p) * (p - xc);
                }
                else
                {
                    yc = m / ((1.0 - p) * (1.0 - p)) * (1.0 - 2.0 * p + 2.0 * p * xc - xc * xc);
                    dyc = 2.0 * m / ((1.0 - p) * (1.0 - p)) * (p - xc);
                }
            }

            double theta2 = Math.Atan(dyc);
            xCoords[half + i] = xc + yt * Math.Sin(theta2);
            yCoords[half + i] = yc - yt * Math.Cos(theta2);
        }

        return (xCoords, yCoords);
    }

    /// <summary>
    /// Assert that a result matches a reference within relative tolerance.
    /// For values where |reference| > 1e-4, uses relative tolerance.
    /// For near-zero values, falls back to absolute tolerance.
    /// </summary>
    private static void AssertRelativeMatch(double actual, double reference, string label)
    {
        if (Math.Abs(reference) < 1e-4)
        {
            AssertNearZero(actual, reference, label);
            return;
        }

        double relativeError = Math.Abs(actual - reference) / Math.Abs(reference);
        Assert.True(relativeError < RelativeTolerance,
            $"{label}: expected {reference:G10}, got {actual:G10}, " +
            $"relative error = {relativeError:E4} (tolerance {RelativeTolerance:E1})");
    }

    /// <summary>
    /// Assert near-zero: for values where the reference is near zero,
    /// uses absolute tolerance instead of relative.
    /// </summary>
    private static void AssertNearZero(double actual, double reference, string label)
    {
        double absoluteError = Math.Abs(actual - reference);
        Assert.True(absoluteError < AbsoluteZeroTolerance,
            $"{label}: expected {reference:G10}, got {actual:G10}, " +
            $"absolute error = {absoluteError:E4} (tolerance {AbsoluteZeroTolerance:E1})");
    }

    /// <summary>
    /// Assert transition location matches within 1% x/c.
    /// </summary>
    private static void AssertTransitionMatch(
        double actual, double reference, string surface)
    {
        double error = Math.Abs(actual - reference);
        Assert.True(error < TransitionTolerance,
            $"Transition ({surface}): expected x/c={reference:F4}, got x/c={actual:F4}, " +
            $"error = {error:F4} (tolerance {TransitionTolerance:F2})");
    }
}
